config/routes.rb
Rails.application.routes.draw do
  resources :documents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  validates :title, :description, presence: true
  # Active storage attachments
  has_one_attached :doc_file
  has_many_attached :doc_file_pages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        CreateImagesOfPdfPagesJob.set(wait: 2.seconds).perform_later(@document.id)
        format.js
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.js
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :description, :doc_file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cable_helper.rb
module CableHelper
  # This cable broadcast methos will be usable in all actioncable call 
  def cable_broadcast(channel, data)
    ActionCable.server.broadcast channel, content: data
  end
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: false) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %><span class="text-danger ml-1">*</span>
    <%= form.text_field :title, class: "form-control form-control-lg", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :description %><span class="text-danger ml-1">*</span>
    <%= form.text_area :description, class: "form-control form-control-lg", rows: 5, required: true %>
  </div>

  <div class="form-group">
    <%= form.label :upload_your_pdf_file_here %><span class="text-danger ml-1">*</span><br>
    <%= form.file_field :doc_file, required: true %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-success" %>
    <%= link_to 'Back', documents_path, class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/documents/_waiting_modal.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-body">
      <p class="lead text-center">We are preparing your document. This will take some time.</p>
      <div id="conversion-progress-bar" class="progress" data-last-uploaded-document-id="<%= document_id %>"></div>
      <p id="converted-page-number" class="ml-2" data-last-uploaded-document-id="<%= document_id %>"><span class="text-primary font-weight-bold">Status:</span> Preparing document</p>

      <div id="alert-message">
        <p>If you need to come back later, your document can be found in the drafts section <a href="/documents/<%= document_id %>" target="_blank" class="text-primary font-weight-bold">here</a>.</p>
      </div>
    </div>

  </div>
</div>

app/views/documents/create.js.erb
$("#exampleModal").html("<%= escape_javascript render('documents/waiting_modal', document_id: @document.id) %>");
$("#exampleModal").modal('show');

app/views/documents/edit.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Editing Document</h4>
        </div>
        <div class="card-body">
          <%= render 'form', document: @document %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/documents/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>Documents</h1>
      <%= link_to "New Document", new_document_path, class: "btn btn-success btn-lg mb-3" %>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @documents.each do |document| %>
            <tr>
              <td><%= document.title %></td>
              <td><%= truncate(document.description, length: 100) %></td>
              <td>
                <div class="dropdown">
                  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Actions
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to "Show", document, class: "dropdown-item" %>
                    <%= link_to "Edit", edit_document_path(document), class: "dropdown-item" %>
                    <%= link_to "Delete", document, method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item" %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/documents/new.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">New Document</h4>
        </div>
        <div class="card-body">
          <%= render 'form', document: @document %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>

app/views/documents/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-lg-auto">
      <h1 class="display-4 text-center"><%= @document.title %></h1>
      <p class="lead"><%= @document.description %></p>
    </div>
  </div>
  <% if @document.doc_file_pages.attached? %>
    <div class="row" style="max-height:600px;overflow: auto;">
      <% @document.doc_file_pages.each do |doc_page| %>
        <div class="col-lg-12 mx-lg-auto">
          <%= image_tag doc_page, class: "img-fluid" %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= link_to 'Edit', edit_document_path(@document) %> |
  <%= link_to 'Back', documents_path %>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">In this demo application we will demonstrate that how you can upload documents using active records and convert preview of PDF pages as images. We have also used action cable to display progress of PDF pages to image conversion inside bootstrap modal. Though this is a simple and basic example but you can learn different concepts here from the code base.</p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to "Try It Now", documents_path, class: "btn btn-success btn-lg" %>
  </p>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-lg-auto">
      <h1 class="display-6 mb-4 mt-4">Features you may learn from this demo</h1>
      <ul class="list-group">
        <li class="list-group-item lead">How to upload files in rails using ActiveStorage?</li>
        <li class="list-group-item lead">How to convert image preview of PDF pages using MiniMagic?</li>
        <li class="list-group-item lead">How to submit rails form using AJAX?</li>
        <li class="list-group-item lead">How to use ActionCable for rendering response for a rails action?</li>
        <li class="list-group-item lead">How to display progress bar for pdf to image conversion?</li>
        <li class="list-group-item lead">Calling ActiveJob from rails controller.</li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfPreviewDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>  
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="blog-footer pt-3 mt-5">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-4 mt-3">
        <p class="lead font-weight-bold">
          <%= link_to 'APPSIMPACT Technologies', root_path %>
        </p>
        <p>
          <%= link_to '@2020', 'javascript:void(0)' %>
        </p>
      </div>
      <div class="col-12 col-md-4">
        <ul>
          <li class="pt-3 font-weight-bold"><%= link_to 'Home', root_path, data: { turbolinks: false } %></li>
          <li class="pt-3 font-weight-bold"><%= link_to 'Documents', documents_path, data: { turbolinks: false } %></li>
        </ul>  
      </div>
      <div class="col-12 col-md-4">
        <ul>
          <li class="pt-3 font-weight-bold text-white">Contact Info:</li>
          <li class="pt-3 text-white">info@appsimpact.com</li>
          <li class="pt-3 text-white">+91 9770-233-163</li>
        </ul>  
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <a class="navbar-brand" href="/">PDF-TO-IMAGE DEMO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/documents">Documents <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>